name: Quark Check-in

on:
  schedule:
    # 每日 09:00 和 13:00 北京时间 -> UTC 为 01:00 和 05:00
    - cron: '0 1 * * *'   # 09:00 北京时间
    - cron: '0 5 * * *'   # 13:00 北京时间
  workflow_dispatch: {}   # 允许手动触发

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # 或根据需要调整

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          # 如果有 requirements.txt，请取消下一行注释
          # pip install -r requirements.txt
          pip install requests

      - name: Run Quark check-in
        env:
          COOKIE_QUARK: ${{ secrets.COOKIE_QUARK }}
        run: |
          python checkIn_Quark.py
